### PR TITLE
Add monthly downloads badge to README

### PR DESCRIPTION
**Pull request by Aman-Clement**
Added a monthly downloads badge by pip Trends to the README.
View more at - https://piptrends.com/widgets/inflector

### CODE REVIEW

**Comment by ixmatus** [comment]
What is the motivation for this change?

**Comment by Aman-Clement** [comment]
Hello @ixmatus ,
Sorry for the delayed response. Our aim is to improve the user experience by providing users with a quick visual indicator of a package's popularity by showing them the monthly download counts.

**Comment by ixmatus** [comment]
Thanks for submitting the PR but I don't believe this adds anything of value so I am rejecting it.

Here's my rationale:

- Users can go to pypi itself for this information, notably, pypi links to `libraries.io` for these statistics. It's clearly trusted by pypi so unless your website is blessed by pypi itself (which I don't have any reason to believe), I will not put my users at risk by linking to an unknown web property that doesn't appear to be trusted by the official pypi web property.
- I don't know if I should trust you. Because this change is so cosmetic -- it's not even proposing a meaningful code change to the function or maintenance of this library -- it comes off as promotional. I'm pretty allergic to people using OSS projects I'm the maintainer for as promotional campaigns.
    - You (or colleagues) appear to be running promotion campaigns for piptrends across the internet beyond just adding badges to people's projects. This makes me more suspicious.
- Piptrends looks much more like an SEO link farm to me than something useful for the community. If you or the owner of piptrends wanted to make something useful for the community, I suggest contributing directly to pypi or libraries.io. That way badges and what-not can point to pypi, which _is_ a trusted source (not just for me, but also for users of this library and repository).
- As a maintainer I have to be on guard for social engineering attacks against projects and first-time contributors opening PRs that are more promotional in nature and not making substantive changes (even if small) ring alarm bells for me.
- You are wasting my time because this kind of contribution is forcing me to evaluate whether I can trust or not so that I can be even-handed in my rejection.

**Comment by ayushjain01** [comment]
Hi @ixmatus 
I understand your concern and I believe we have been quite transparent about everything since the beginning. I understand that we do not come up as a trusted source yet and that is the reason why we are trying to share something that we have built and gain some trust. Every project, even libraries.io which you seem to be weirdly supportive of, was once a small project like ours. We have also made sure to point out the fact that if the maintainer wants to remove the link to the piptrends page, they can. I also do not see how we can be suspicious just by trying to share something that we have built. If you genuinely had any concerns regarding that, then you should have first discussed it with us here, instead of spreading a random suspicion and going around **stalking** us and commenting on every PR we have raised. You complain about us wasting your time and then you have enough time to be going around spreading false rumors about our project. 

Also every developer was once a first time contributor and it is very sad and discouraging to have people like you, who do not discuss things first and just spread hate over the internet and stop people from sharing things they have built. 

I would appreciate if you would discuss your concerns with us before going around and talking negative about our project. It's totally your wish to whether have the badge on your readme or not. I have clearly mentioned why this badge is better than the existing badges and if you do have any doubts with that you can go ahead and check the download counts yourself and see why there is a need for the badge we have built. 

You can refer this [discussion](https://github.com/sqlalchemy/sqlalchemy/discussions/11460).

**Comment by ixmatus** [comment]
I’m sympathetic to early career developers but you can surely empathize with why blasting your unknown project across lots of oss projects is promotional activity? Why that is suspicious? And the fact that oss project maintainers have to deal with social engineering attacks and commercial and seo promotional campaigns on a regular basis?

This is a low effort reply and doesn’t even attempt to address your behavior and that of your colleague across the oss Python ecosystem. It makes me trust you less.

**Pull request closed without merging**
